/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.RegistroCurso;
import modelo.RegistroEstudiantes;

/**
 *
 * @author ronald
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    RegistroEstudiantes registroEstudiantes;
    RegistroCurso registroCurso;
    
    public Menu() {
        initComponents();
        registroEstudiantes=new RegistroEstudiantes();
        registroCurso=new RegistroCurso();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        jmAdministrar = new javax.swing.JMenu();
        jmiEstudiante = new javax.swing.JMenuItem();
        jmiMatricula = new javax.swing.JMenuItem();
        jmiCurso = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmAdministrar.setText("Administrar");

        jmiEstudiante.setText("Estudiante");
        jmiEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEstudianteActionPerformed(evt);
            }
        });
        jmAdministrar.add(jmiEstudiante);

        jmiMatricula.setText("Matricula");
        jmAdministrar.add(jmiMatricula);

        jmiCurso.setText("Curso");
        jmiCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCursoActionPerformed(evt);
            }
        });
        jmAdministrar.add(jmiCurso);

        barraMenu.add(jmAdministrar);

        jmReportes.setText("Reportes");
        barraMenu.add(jmReportes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEstudianteActionPerformed
        // TODO add your handling code here:
        GUIAdminEstudiante gUIAdminEstudiante=new GUIAdminEstudiante();
        gUIAdminEstudiante.setRegistroEstudiantes(registroEstudiantes);
        gUIAdminEstudiante.init();
        gUIAdminEstudiante.setVisible(true);
    }//GEN-LAST:event_jmiEstudianteActionPerformed

    private void jmiCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCursoActionPerformed
        GUIAdminCurso gUIAdminCurso=new GUIAdminCurso();
        gUIAdminCurso.setRegistroCurso(registroCurso);
        gUIAdminCurso.init();
        gUIAdminCurso.setVisible(true);
    }//GEN-LAST:event_jmiCursoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jmAdministrar;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenuItem jmiCurso;
    private javax.swing.JMenuItem jmiEstudiante;
    private javax.swing.JMenuItem jmiMatricula;
    // End of variables declaration//GEN-END:variables
}
