/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;

/**
 *
 * @author ronald
 */
public class PanelBotonesAccion extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotonesAccion
     */
    public PanelBotonesAccion() {
        initComponents();
        jbAceptar.setActionCommand(BOTON_TYPE_ACEPTAR);
        jbAceptar.setText(BOTON_TYPE_ACEPTAR);
    }
    
    public void setControlador(Controlador controlador){
        jbAceptar.addActionListener(controlador);
    }
    
    public void init(Ventana ventana){
        this.ventana=ventana;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(588, 33));

        jbAceptar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbAceptar.setText("Aceptar");

        jbCancelar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar)
                .addGap(0, 337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbAceptar)
                .addComponent(jbCancelar))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        ventana.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed
 public static String BOTON_TYPE_ACEPTAR="Aceptar";
    private Ventana ventana;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    // End of variables declaration//GEN-END:variables

}
