/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelBotonesMantenimiento.java
 *
 * Created on 17/03/2011, 03:58:17 PM
 */

package vista;

import controlador.Controlador;

/**
 *
 * @author ronald
 */
public class PanelBotonesMantenimiento extends javax.swing.JPanel {

    /** Creates new form PanelBotonesMantenimiento */
    public PanelBotonesMantenimiento() {
        initComponents();
    }
    public void setVentana(Ventana ventana) {
        this.ventana=ventana;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAgregar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jlCampoClave = new javax.swing.JLabel();
        jcCampoClave = new javax.swing.JComboBox();
        jlTextoClave = new javax.swing.JLabel();
        jtTextoClave = new javax.swing.JTextField();
        jbFiltrar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(56, 52, 221));

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jbAgregar.setToolTipText("Agregar");
        jbAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAgregar.setMaximumSize(new java.awt.Dimension(54, 54));
        jbAgregar.setPreferredSize(new java.awt.Dimension(54, 54));
        jbAgregar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        jbEditar.setToolTipText("Modificar");
        jbEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jbEliminar.setToolTipText("Eliminar");
        jbEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jlCampoClave.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jlCampoClave.setForeground(java.awt.Color.white);
        jlCampoClave.setText("Filtrar por:");

        jcCampoClave.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlTextoClave.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jlTextoClave.setForeground(java.awt.Color.white);
        jlTextoClave.setText("Texto Clave");

        jbFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/filtro.png"))); // NOI18N

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salir.png"))); // NOI18N
        jbSalir.setToolTipText("Salir");
        jbSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSalir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCampoClave)
                        .addGap(1, 1, 1)
                        .addComponent(jcCampoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlTextoClave)
                        .addGap(3, 3, 3)
                        .addComponent(jtTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbSalir)))
                .addGap(6, 6, 6)
                .addComponent(jbFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCampoClave)
                            .addComponent(jcCampoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTextoClave))))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        ventana.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

/**
 * Este método permite agregar los campos clave por los cuales puede filtrar el
 * buscador
 * @param camposClave
 */
public void addCamposClave(String []camposClave){
 jcCampoClave.setModel(new javax.swing.DefaultComboBoxModel(camposClave));
 
 jbAgregar.setActionCommand(PanelBotonesMantenimiento.BOTON_TYPE_AGREGAR);
 jbEditar.setActionCommand(PanelBotonesMantenimiento.BOTON_TYPE_EDITAR);
 jbEliminar.setActionCommand(PanelBotonesMantenimiento.BOTON_TYPE_ELIMINAR);
 jbFiltrar.setActionCommand(PanelBotonesMantenimiento.BOTON_TYPE_FILTRAR);
 jbSalir.setActionCommand(PanelBotonesMantenimiento.BOTON_TYPE_CERRAR);
}
public void setControlador( Controlador manejador){
    jbAgregar.addActionListener(manejador);
    jbEliminar.addActionListener(manejador);
    jbEditar.addActionListener(manejador);
    jbFiltrar.addActionListener(manejador);
}

public String getCampoClave(){
   return jcCampoClave.getSelectedItem().toString();
}
public String getTextoClave(){
    return jtTextoClave.getText();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbFiltrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox jcCampoClave;
    private javax.swing.JLabel jlCampoClave;
    private javax.swing.JLabel jlTextoClave;
    private javax.swing.JTextField jtTextoClave;
    // End of variables declaration//GEN-END:variables

    public static String BOTON_TYPE_AGREGAR="Agregar";
    public static String BOTON_TYPE_EDITAR="Editar";
    public static String BOTON_TYPE_CERRAR="Cerrar";
    public static String BOTON_TYPE_FILTRAR="Filtrar";
    public static String BOTON_TYPE_ELIMINAR="Eliminar";
    Ventana ventana;
}