/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ronald
 */
public class PanelListado extends javax.swing.JPanel {

    /**
     * Creates new form PanelListado
     */
    public PanelListado() {
        initComponents();
    }
    
     public void setValores(String[][] datosFilas, String etiquetas[]) {
        if (datosFilas != null) {
            jtDatos.setModel(new javax.swing.table.DefaultTableModel(datosFilas, etiquetas));
            barraDesplazamiento.setViewportView(jtDatos);
        }

    }

    public String[] getdatosFila() {
        String datos[] = new String[jtDatos.getColumnCount()];
        int filaSeleccionada = jtDatos.getSelectedRow();
        for (int columna = 0; columna < datos.length; columna++) {
            datos[columna] = jtDatos.getValueAt(filaSeleccionada, columna).toString().trim();
        }
        return datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDesplazamiento = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        barraDesplazamiento.setViewportView(jtDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraDesplazamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraDesplazamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane barraDesplazamiento;
    private javax.swing.JTable jtDatos;
    // End of variables declaration//GEN-END:variables
}
