/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Estudiante;

/**
 *
 * @author ronald
 */
public class PanelEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form PanelEstudiante
     */
    public PanelEstudiante() {
        initComponents();
    }
    
    public void setEstudiante(Estudiante estudiante){
        jtIdentificado.setText(estudiante.getIdentificador());
        jtNombre.setText(estudiante.getNombre());
        jtCedula.setText(estudiante.getCedula());
        jtAnoIngreso.setText(Integer.toString(estudiante.getAñoIngreso()));
    }
    
    public void modificarEstudiantes(Estudiante estudiantes){
        estudiantes.setIdentificador(jtIdentificado.getText());
    }
        
    
    public Estudiante getEstudiante(){
        return new Estudiante(jtNombre.getText(),Integer.parseInt(jtAnoIngreso.getText()),jtIdentificado.getText(),jtCedula.getText());
    }
    
    public  boolean verificar(){
        boolean verifico=false;
        if(!jtCedula.getText().equals("")&&!jtNombre.getText().equals("")&&!jtIdentificado.getText().equals("")&&!jtAnoIngreso.getText().equals("")){
            verifico=true;
            
        }else{
            JOptionPane.showMessageDialog(null,"Por favor complete los datos");
        }
        return verifico;
    }
    public void mensaje(){
        JOptionPane.showMessageDialog(null,"Ya existe esta identificacion");
    }

    public String getJtIdentificado() {
        return jtIdentificado.getText();
    }

    public void setJtIdentificado(String identificado) {
        this.jtIdentificado.setText(identificado);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIdentificador = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlCedula = new javax.swing.JLabel();
        jlAnoIngreso = new javax.swing.JLabel();
        jtIdentificado = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCedula = new javax.swing.JTextField();
        jtAnoIngreso = new javax.swing.JTextField();

        jlIdentificador.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlIdentificador.setText("Identificador");

        jlNombre.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlNombre.setText("Nombre");

        jlCedula.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlCedula.setText("Cédula");

        jlAnoIngreso.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlAnoIngreso.setText("Año Ingreso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAnoIngreso)
                        .addGap(18, 18, 18)
                        .addComponent(jtAnoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlIdentificador)
                            .addComponent(jlNombre)
                            .addComponent(jlCedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtIdentificado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtIdentificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlIdentificador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAnoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAnoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAnoIngreso;
    private javax.swing.JLabel jlCedula;
    private javax.swing.JLabel jlIdentificador;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextField jtAnoIngreso;
    private javax.swing.JTextField jtCedula;
    private javax.swing.JTextField jtIdentificado;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
