/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author home
 */
public class PanelListadoCurso extends javax.swing.JPanel {

    /**
     * Creates new form PanelListadoCurso
     */
    public PanelListadoCurso() {
        initComponents();
    }
    
    public void setValores(String[][] datosFilas, String etiquetas[]) {
        if (datosFilas != null) {
            jDatos.setModel(new javax.swing.table.DefaultTableModel(datosFilas, etiquetas));
            barraDesplazamiento.setViewportView(jDatos);
        }

    }

    public String[] getdatosFila() {
        String datos[] = new String[jDatos.getColumnCount()];
        int filaSeleccionada = jDatos.getSelectedRow();
        for (int columna = 0; columna < datos.length; columna++) {
            datos[columna] = jDatos.getValueAt(filaSeleccionada, columna).toString().trim();
        }
        return datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDesplazamiento = new javax.swing.JScrollPane();
        jDatos = new javax.swing.JTable();

        jDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        barraDesplazamiento.setViewportView(jDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraDesplazamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraDesplazamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane barraDesplazamiento;
    private javax.swing.JTable jDatos;
    // End of variables declaration//GEN-END:variables
}
